src/chat/urls.py
from django.urls import path

from chat.views import ChatDetailView

urlpatterns = [
    path('<int:pk>/', ChatDetailView.as_view(), name='room'),
]

app_name = 'chat'

src/config/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('users/', include('users.urls')),
    path('posts/', include('posts.urls')),
    path('chat/', include('chat.urls')),
    path('', include('pages.urls')),
]

src/users/urls.py
from django.urls import path

from users import views

urlpatterns = [
    path('edit/', views.UserUpdateView.as_view(), name='edit'),
    path('<int:pk>/', views.UserDetailView.as_view(), name='detail'),
    path('<int:pk>/follow/', views.FollowUserView.as_view(), name='follow'),
    path('<int:pk>/unfollow/', views.UnFollowUserView.as_view(), name='unfollow'),
]

app_name = 'users'

src/users/models.py
from hashlib import md5

from django.contrib.auth.models import AbstractUser, UserManager
from django.db import models
from django.urls import reverse

from model_utils import models as mu


class User(mu.TimeStampedModel,
           mu.SoftDeletableModel,
           AbstractUser):
    """
    User entity.
    """
    about_me = models.TextField(default='', blank=True)
    following = models.ManyToManyField('self',
                                       related_name='followers',
                                       symmetrical=False)

    objects = UserManager()

    @property
    def avatar_url(self) -> str:
        avatar_hash = md5(self.email.encode()).hexdigest()
        return f'https://www.gravatar.com/avatar/{avatar_hash}?d=identicon'

    def get_absolute_url(self) -> str:
        return reverse('users:detail', kwargs={'pk': self.pk})

    def follow(self, user):
        if self.is_following(user):
            return
        if user == self:
            return
        self.following.add(user)

    def unfollow(self, user):
        if self.is_following(user):
            self.following.remove(user)

    def is_following(self, user):
        return self.following.filter(pk=user.pk).exists()

src/users/forms.py
from django import forms
from django.contrib.auth import forms as auth_forms

from users.models import User


class UserCreationForm(auth_forms.UserCreationForm):
    password1 = forms.CharField(
        label='Password',
        widget=forms.PasswordInput,
    )
    password2 = forms.CharField(
        label='Repeat password',
        widget=forms.PasswordInput,
    )

    class Meta:
        model = User
        fields = ('username', 'email',)

    def clean_password2(self):
        password1 = self.cleaned_data.get('password1')
        password2 = self.cleaned_data.get('password2')
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError('Passwords do not match!')
        return password2

    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data['password1'])
        if commit:
            user.save()
        return user


class UserChangeForm(auth_forms.UserChangeForm):
    class Meta:
        model = User
        fields = ('username', 'email', 'about_me',)


class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('username', 'about_me',)
        help_texts = {
            'username': None,
        }

src/users/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.detail import DetailView, SingleObjectMixin
from django.views.generic.edit import UpdateView

from core.views import ActionView
from users.forms import UserForm
from users.models import User


class UserDetailView(DetailView):
    model = User
    template_name = 'users/detail.html'


class UserUpdateView(LoginRequiredMixin, UpdateView):
    form_class = UserForm
    template_name = 'users/edit.html'

    def get_object(self):
        return self.request.user


class FollowUserView(LoginRequiredMixin,
                     SingleObjectMixin,
                     ActionView):
    model = User

    def perform_action(self):
        user = self.get_object()
        self.request.user.follow(user)

    def get_redirect_url(self, *args, **kwargs):
        user = self.get_object()
        return user.get_absolute_url()


class UnFollowUserView(LoginRequiredMixin,
                       SingleObjectMixin,
                       ActionView):
    model = User

    def perform_action(self):
        user = self.get_object()
        self.request.user.unfollow(user)

    def get_redirect_url(self, *args, **kwargs):
        user = self.get_object()
        return user.get_absolute_url()

src/templates/users/detail.html
{% extends 'base.html' %}

{% block content %}
<div class="row mt-3">
  <div class="col-md-3 d-flex flex-row-reverse">
    <img class="rounded-circle mr-2" src="{{ user.avatar_url }}&s=160">
  </div>
  <div class="col-md-9">
    <h3>@{{ user.username }}</h3>
    <p>Joined: {{ user.created }}</p>
    <p>Last seen: {{ user.last_login }}</p>
    <p>{{ user.about_me }}</p>
    <p>Followers: {{ user.followers.count }} | Following: {{ user.following.count }}</p>
    {% if user == request.user %}
      <a class="btn btn-warning" href="{% url 'users:edit' %}">Edit</a>
    {% else %}
      {% if user in request.user.following.all %}
        <a class="btn btn-warning" href="{% url 'users:unfollow' pk=user.pk %}">Unfollow</a>
      {% else %}
        <a class="btn btn-success" href="{% url 'users:follow' pk=user.pk %}">Follow</a>
      {% endif %}
      <a class="btn btn-success" href="{% url 'chat:room' pk=user.pk %}">Message</a>
    {% endif %}
  </div>
</div>
<div class="row mt-3">
  <h4>Posts by @{{ user.username }}:</h4>
  {% for post in user.posts.all %}
    {% include 'components/_post.html' %}
  {% empty %}
    <p>{{ user.username }} hasn't posted yet.</p>
  {% endfor %}
</div>
{% endblock content %}

src/templates/users/edit.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
<h2>Edit personal info</h2>
<div class="row">
  <div class="col-md-4">
    <form method="POST">
      {% csrf_token %}
      {{ form|crispy }}
      <button class="btn btn-success" type="submit">Save</button>
    </form>
  </div>
</div>
{% endblock content %}