src/chat/urls.py
from django.urls import path

from chat.views import ChatDetailView

urlpatterns = [
    path('<int:pk>/', ChatDetailView.as_view(), name='room'),
]

app_name = 'chat'

src/config/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('users/', include('users.urls')),
    path('posts/', include('posts.urls')),
    path('chat/', include('chat.urls')),
    path('', include('pages.urls')),
]

src/pages/urls.py
from django.urls import path

from pages.views import HomePageView

urlpatterns = [
    path('', HomePageView.as_view(), name='home'),
]

app_name = 'pages'

src/posts/urls.py
from django.urls import path

from posts import views

urlpatterns = [
    path('', views.PostListView.as_view(), name='list'),
    path('likes/', views.LikedPostsView.as_view(), name='likes'),
    path('<int:pk>/like/', views.LikePostView.as_view(), name='like'),
    path('<int:pk>/unlike/', views.UnlikePostView.as_view(), name='unlike'),
]

app_name = 'posts'

src/users/urls.py
from django.urls import path

from users import views

urlpatterns = [
    path('edit/', views.UserUpdateView.as_view(), name='edit'),
    path('<int:pk>/', views.UserDetailView.as_view(), name='detail'),
    path('<int:pk>/follow/', views.FollowUserView.as_view(), name='follow'),
    path('<int:pk>/unfollow/', views.UnFollowUserView.as_view(), name='unfollow'),
]

app_name = 'users'

src/posts/models.py
from django.conf import settings
from django.db import models

from model_utils import models as mu


class Post(mu.TimeStampedModel,
           models.Model):
    """
    Post entity.
    """
    text = models.CharField(max_length=180)
    author = models.ForeignKey(settings.AUTH_USER_MODEL,
                               on_delete=models.CASCADE,
                               related_name='posts')

    class Meta:
        ordering = ('-created',)

    def get_liked_users(self):
        return [like.user for like in self.likes.all()]

    def __str__(self) -> str:
        return self.text


class Like(models.Model):
    """
    Like entity.
    """
    post = models.ForeignKey(Post,
                             on_delete=models.CASCADE,
                             related_name='likes')
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE,
                             related_name='likes')

    def __str__(self) -> str:
        return f'Like of {self.post} by {self.user}'

src/posts/forms.py
from django import forms

from posts.models import Post


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('text',)
        labels = {
            'text': '',
        }
        widgets = {
            'text': forms.TextInput(attrs={
                'placeholder': 'What is on your mind?',
            }),
        }

src/posts/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.views.generic.detail import SingleObjectMixin
from django.views.generic.list import ListView

from core.views import ActionView
from posts.models import Like, Post


class PostListView(ListView):
    model = Post
    template_name = 'posts/list.html'

    def get_queryset(self):
        return Post.objects.select_related('author')


class LikePostView(LoginRequiredMixin,
                   SingleObjectMixin,
                   ActionView):
    model = Post
    url = reverse_lazy('pages:home')

    def perform_action(self):
        post = self.get_object()
        Like.objects.get_or_create(post=post,
                                   user=self.request.user)

    def get_redirect_url(self, *args, **kwargs):
        next = self.request.GET.get('next', None)
        return (next if next is not None
                else super().get_redirect_url(*args, **kwargs))


class UnlikePostView(LoginRequiredMixin,
                     SingleObjectMixin,
                     ActionView):
    model = Post
    url = reverse_lazy('pages:home')

    def perform_action(self):
        post = self.get_object()
        like = Like.objects.filter(post=post,
                                   user=self.request.user).first()
        if like is not None:
            like.delete()

    def get_redirect_url(self, *args, **kwargs):
        next = self.request.GET.get('next', None)
        return (next if next is not None
                else super().get_redirect_url(*args, **kwargs))


class LikedPostsView(LoginRequiredMixin,
                     ListView):
    model = Post
    template_name = 'posts/likes.html'

    def get_queryset(self):
        return self.request.user.likes.select_related('user')

src/templates/components/_messages.html
{% for message in chat.messages.all %}{{ message.author }}: {{ message.text }}
{% empty %}You will be the first one.{% endfor %}

src/templates/components/_navbar.html
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container">
    <a class="navbar-brand" href="{% url 'pages:home' %}">Navbar</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
      aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Posts
          </a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="{% url 'posts:list' %}">Explore</a></li>
            <li><a class="dropdown-item" href="{% url 'posts:likes' %}">Likes posts</a></li>
          </ul>
        </li>
      </ul>
      {% if request.user.is_authenticated %}
        <div class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            {{ request.user.username }}
          </a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="{% url 'users:detail' pk=request.user.pk %}">Account</a></li>
            <li><a class="dropdown-item" href="{% url 'account_change_password' %}">Change password</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="{% url 'account_logout' %}">Logout</a></li>
          </ul>
        </div>
      {% else %}
        <a class="nav-link active" aria-current="page" href="{% url 'account_login' %}">Login</a>
      {% endif %}
    </div>
  </div>
</nav>

src/templates/components/_post.html
<div class="row mt-3">
  <div class="col-md-1 d-flex flex-row-reverse">
    <a href="{{ post.author.get_absolute_url }}">
      <img class="rounded-circle" src="{{ post.author.avatar_url }}&s=48">
    </a>
  </div>
  <div class="col-md-8">
    <a href="{{ post.author.get_absolute_url }}">
      {{ post.author.username }}
    </a>
    <p>{{ post.text }}</p>
  </div>
  <div class="col-md-3 d-flex flex-row-reverse">
    {{ post.created }}
  </div>
</div>
<div class="row">
  <div class="col-md-1"></div>
  <div class="col-md-4">
    {% if request.user.is_authenticated %}
      {% if request.user in post.get_liked_users %}
        <a href="{% url 'posts:unlike' pk=post.pk %}?next={{ request.path }}">💔</a>
      {% else %}
        <a href="{% url 'posts:like' pk=post.pk %}?next={{ request.path }}">🧡</a>
      {% endif %}
    {% endif %}
    {{ post.likes.count }} like(s)
  </div>
</div>